# Generated by Django 2.1 on 2019-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(help_text='최대 140자 입력 가능', max_length=140),
        ),
    ]
